/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThanksRouteImport } from './routes/thanks'
import { Route as StartRouteImport } from './routes/start'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CSlugRouteImport } from './routes/c.$slug'
import { Route as AboutRefundGuaranteesRouteImport } from './routes/about.refund-guarantees'
import { Route as AboutHowItWorksRouteImport } from './routes/about.how-it-works'
import { Route as AboutFaqRouteImport } from './routes/about.faq'

const ThanksRoute = ThanksRouteImport.update({
  id: '/thanks',
  path: '/thanks',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRefundGuaranteesRoute = AboutRefundGuaranteesRouteImport.update({
  id: '/about/refund-guarantees',
  path: '/about/refund-guarantees',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutHowItWorksRoute = AboutHowItWorksRouteImport.update({
  id: '/about/how-it-works',
  path: '/about/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutFaqRoute = AboutFaqRouteImport.update({
  id: '/about/faq',
  path: '/about/faq',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/donate': typeof DonateRoute
  '/login': typeof LoginRoute
  '/start': typeof StartRoute
  '/thanks': typeof ThanksRoute
  '/about/faq': typeof AboutFaqRoute
  '/about/how-it-works': typeof AboutHowItWorksRoute
  '/about/refund-guarantees': typeof AboutRefundGuaranteesRoute
  '/c/$slug': typeof CSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/donate': typeof DonateRoute
  '/login': typeof LoginRoute
  '/start': typeof StartRoute
  '/thanks': typeof ThanksRoute
  '/about/faq': typeof AboutFaqRoute
  '/about/how-it-works': typeof AboutHowItWorksRoute
  '/about/refund-guarantees': typeof AboutRefundGuaranteesRoute
  '/c/$slug': typeof CSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/donate': typeof DonateRoute
  '/login': typeof LoginRoute
  '/start': typeof StartRoute
  '/thanks': typeof ThanksRoute
  '/about/faq': typeof AboutFaqRoute
  '/about/how-it-works': typeof AboutHowItWorksRoute
  '/about/refund-guarantees': typeof AboutRefundGuaranteesRoute
  '/c/$slug': typeof CSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/dashboard'
    | '/donate'
    | '/login'
    | '/start'
    | '/thanks'
    | '/about/faq'
    | '/about/how-it-works'
    | '/about/refund-guarantees'
    | '/c/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/dashboard'
    | '/donate'
    | '/login'
    | '/start'
    | '/thanks'
    | '/about/faq'
    | '/about/how-it-works'
    | '/about/refund-guarantees'
    | '/c/$slug'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/dashboard'
    | '/donate'
    | '/login'
    | '/start'
    | '/thanks'
    | '/about/faq'
    | '/about/how-it-works'
    | '/about/refund-guarantees'
    | '/c/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  DonateRoute: typeof DonateRoute
  LoginRoute: typeof LoginRoute
  StartRoute: typeof StartRoute
  ThanksRoute: typeof ThanksRoute
  AboutFaqRoute: typeof AboutFaqRoute
  AboutHowItWorksRoute: typeof AboutHowItWorksRoute
  AboutRefundGuaranteesRoute: typeof AboutRefundGuaranteesRoute
  CSlugRoute: typeof CSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thanks': {
      id: '/thanks'
      path: '/thanks'
      fullPath: '/thanks'
      preLoaderRoute: typeof ThanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/refund-guarantees': {
      id: '/about/refund-guarantees'
      path: '/about/refund-guarantees'
      fullPath: '/about/refund-guarantees'
      preLoaderRoute: typeof AboutRefundGuaranteesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/how-it-works': {
      id: '/about/how-it-works'
      path: '/about/how-it-works'
      fullPath: '/about/how-it-works'
      preLoaderRoute: typeof AboutHowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/faq': {
      id: '/about/faq'
      path: '/about/faq'
      fullPath: '/about/faq'
      preLoaderRoute: typeof AboutFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  DonateRoute: DonateRoute,
  LoginRoute: LoginRoute,
  StartRoute: StartRoute,
  ThanksRoute: ThanksRoute,
  AboutFaqRoute: AboutFaqRoute,
  AboutHowItWorksRoute: AboutHowItWorksRoute,
  AboutRefundGuaranteesRoute: AboutRefundGuaranteesRoute,
  CSlugRoute: CSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
